CREATE TABLE IF NOT EXISTS ledger_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(128) NOT NULL,
    asset_symbol VARCHAR(32) NOT NULL,
    available BIGINT NOT NULL CHECK (available >= 0),
    locked BIGINT NOT NULL CHECK (locked >= 0),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_ledger_balance_account_asset UNIQUE (account_id, asset_symbol)
);
CREATE TABLE IF NOT EXISTS processed_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_type VARCHAR(64) NOT NULL,
    client_order_id VARCHAR(128) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    asset_symbol VARCHAR(32) NOT NULL,
    amount BIGINT NOT NULL CHECK (amount > 0),
    payload_hash VARCHAR(64),
    CONSTRAINT uk_processed_command_type_client_order UNIQUE (command_type, client_order_id)
);

CREATE TABLE IF NOT EXISTS settlement_instructions (
    id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    execution_id TEXT PRIMARY KEY,
    payload TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('PENDING','APPLIED','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invalid_settlements (
    id TEXT PRIMARY KEY,
    topic TEXT NOT NULL,
    partition_id INTEGER NOT NULL,
    source_offset BIGINT NOT NULL,
    payload TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
